default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: audio_development
test:
  <<: *default
  database: audio_test

production:
  <<: *default
  database: audio_production
